[package]
name = "rust-api"
version = "0.1.0"
edition = "2021"
authors = ["joel <joelvictor1746@gmail.com"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
